### ISSUE TITLE
Fields "First Name" and "Last Name" are not pre-filled automatically when the additional participant is selected

### ISSUE THREAD

**Issue by cristina-p** [twomice/com.joineryhq.groupreg#15]
When registering the **Additional Participant** for a Group Event using this extension, after **selecting the related contact** through the relationship to the Primary Participant, the fields **"First Name", "Last Name"** and "Email", which are contained in the Profile for Additional Participant in the Event Configuration, **are** **not filled** with the data of the selected contact record.
This is the screenshot:

![Profile Filelds are not prefilled](https://github.com/twomice/com.joineryhq.groupreg/assets/36039284/b2082562-1e0a-4389-bf75-acd962a92cb5)

Also, when the Additional Participant is selected, the fields of the Profile for the Online Registration are not being displayed. They only appear when the button "Continue" is clicked:

![No Profile Fields are shown](https://github.com/twomice/com.joineryhq.groupreg/assets/36039284/651a327e-c107-4c3f-9297-0d57000896bd)

**Comment by cristina-p** [comment]
I am working with **CiviCRM 5.58.1**, php 7.4, MySQL 5.7.41, **WordPress 5.9.7**

**Comment by twomice** [comment]
Confirmed: I'm able to reproduce this in my development environment.

I believe this is fixed in b23777879eeb046fae870e92d6085491e6be6f3e . 

@cristina-p , could you try the latest master and test whether it resolves this issue?

**Comment by cristina-p** [comment]
Yes, these have been fixed.
But it is still not possible to create a new contact if the Primary Participant wants to register a related contacted that is not in the system, as the fields to register an Additional Participant only appear when a existing contact is selected.

**Comment by twomice** [comment]
@cristina-p Thanks for confirming the fix. As to "not possible to create a new contact", I've created a new ticket in #18 .
