### ISSUE TITLE
Participant Role for the Primary Participant not attending is not the one configured in the Event Configuration

### ISSUE THREAD

**Issue by cristina-p** [twomice/com.joineryhq.groupreg#16]
The **Participant Role for the Primary Participant not attending** is not the one configured in the Event Configuration (Non-attending registrant) as you can see in the following screenshot:

![Non-attending registrant Role](https://github.com/twomice/com.joineryhq.groupreg/assets/36039284/67da0368-6417-4dda-a5da-c4448a29c62f)
And this is the Event Configuration:

![Event Configuration](https://github.com/twomice/com.joineryhq.groupreg/assets/36039284/aa461224-34ce-4cba-ac7b-194eee3039e6)

I am working with **CiviCRM 5.58.1**, php 7.4, MySQL 5.7.41, **WordPress 5.9.7**

**Comment by twomice** [comment]
Confirmed: I can observe this bad behavior in my development environment. Will work on a diagnosis and a fix.

**Comment by twomice** [comment]
@cristina-p  Looks this bug was appearing when the "Primary participant is attendee" is set to "yes" or "no" (i.e., not "allow user to select").

Should be fixed in 6c0c98a . 

Could you please try the latest master and see if it resolves your issue?

**Comment by cristina-p** [comment]
thank you! This have been fixed
