### ISSUE TITLE
Fields of Type Radio button or Checkbox are not populated with the data of the contact selected as Additional Participant

### ISSUE THREAD

**Issue by cristina-p** [twomice/com.joineryhq.groupreg#17]
When the fields configured on the Event **Profile for Additional Participants** in the Online Registration configuration are the type "**Radio button**s" or "**Checkbox**es", are not being **pre-populated** with the data that contained for the related contacted selected in the event registration form.
See screenshot below, for the fields "_Sex_", "_Has your child been diagnosed with ADHD?_", "_Does your child have any other conditions?_", where they have a value for the contact selected:

![image](https://github.com/twomice/com.joineryhq.groupreg/assets/36039284/6524d3aa-2c01-42dd-b3d6-f7708c905384)

Also, is there any way, as it can be done with the Email, to **enable** the fields **"First Name" and "Last Name"**  in the **Additional Participant Profile** of the Event configuration, so that they can be updated by the Primary Participant during the event registration?

**Comment by twomice** [comment]
@cristina-p thanks for reporting. 

Confirmed: I can reproduce this bug in my development environment.

I'll be working to diagnose and fix; will update on progress here.

**Comment by twomice** [comment]
Regarding this question:
> Also, is there any way, as it can be done with the Email, to enable the fields "First Name" and "Last Name" in the Additional Participant Profile of the Event configuration, so that they can be updated by the Primary Participant during the event registration?

The short answer is: I'm not planning to support this functionality. Please feel free to submit a separate ticket on this topic if you'd like further discussion.

**Comment by twomice** [comment]
@cristina-p 

I've added a fix for this issue in the master branch, with commit c02e184.

With this fix, values should load properly for various field types, both custom and core:
- single-value checkboxes
- multi-value checkboxes
- dates with time
- dates without time
- radio buttons
- single-value selects
- multi-value selects

Screenshot example of working Additional Participant profile fields:

---
![17-fix](https://github.com/twomice/com.joineryhq.groupreg/assets/759449/9889861e-1b2c-4ef8-acb6-c8970a4fcd21)
---

Could you please update to the latest master and confirm whether this fixes the issue?

Thanks!

**Comment by twomice** [comment]
I believe this is fixed and haven't heard back from OP. Closing for now.

@cristina-p Please feel free to re-open if this is still an issue. Thanks!
